-- Create the income_records table
create table if not exists income_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  amount numeric not null,
  date date not null,
  source text -- optional: e.g., 'Tips', 'Salary', 'Side Gig'
);

-- Enable RLS
alter table income_records enable row level security;

-- Policies
create policy "Users can delete their own income records"
  on income_records for delete
  using (auth.uid() = user_id);

create policy "Users can insert their own income records"
  on income_records for insert
  with check (auth.uid() = user_id);

create policy "Users can select their own income records"
  on income_records for select
  using (auth.uid() = user_id);

create policy "Users can update their own income records"
  on income_records for update
  using (auth.uid() = user_id);
